export const getConfig = async () => ({});
export const updateConfig = async () => null;
export const getModelsConfig = async () => ({});
export const setModelsConfig = async () => null;
export const getConnectionsConfig = async () => ({});
export const setConnectionsConfig = async () => null;
export const getToolServerConnections = async () => ([]);
export const setToolServerConnections = async () => null;
export const getBanners = async () => ([]);
export const setBanners = async () => null;
export const setDefaultPromptSuggestions = async () => null;
export const exportConfig = async () => null;
export const importConfig = async () => null;
export const getCodeExecutionConfig = async () => ({});
export const setCodeExecutionConfig = async () => null;
export const verifyToolServerConnection = async () => ({ success: false });
export const registerOAuthClient = async () => null;
